### PR TITLE
Borrow delay mutably

### PR DESCRIPTION
**Pull request by David-OConnor**
Don't own delay; otherwise this crate causes compatibility issues, since delay is a popular thing to do.

### CODE REVIEW

**Comment by arrowcircle** [comment]
Could you please show an example of new usage?

**Comment by dtantsur** [comment]
@uber-foo any opinion on this PR?

**Comment by sciguy16** [comment]
@arrowcircle here's an example of the new usage on an STM32F103:

```rust
let cp = cortex_m::Peripherals::take().unwrap();
let mut delay = Delay::new(cp.SYST, clocks);
let i2c = stm32f1xx_hal::i2c::BlockingI2c::i2c1( ... );
let mut bme280 = BME280::new_primary(i2c);
bme280.init(&mut delay).unwrap();
let measurements = bme280.measure(&mut delay).unwrap();
```

I've tested it on an STM32 and it's working well.

**Comment by arrowcircle** [comment]
> @arrowcircle here's an example of the new usage on an STM32F103:
> 
> ```rust
> let cp = cortex_m::Peripherals::take().unwrap();
> let mut delay = Delay::new(cp.SYST, clocks);
> let i2c = stm32f1xx_hal::i2c::BlockingI2c::i2c1( ... );
> let mut bme280 = BME280::new_primary(i2c);
> bme280.init(&mut delay).unwrap();
> let measurements = bme280.measure(&mut delay).unwrap();
> ```
> 
> I've tested it on an STM32 and it's working well.

@sciguy16 Hey! Thanks for the answer. Does it work with the rtic?

**Comment by sciguy16** [comment]
I haven't tried it with rtic, but as long as it's got something that provides a DelayMs<u8> then it should work the same as before.

**Pull request closed without merging**
