### PR TITLE
Add basic BMP280 support

### LINKED ISSUE #1: Supporting BMP280
Hi!

I have a BMP280, with is basically a BME280 without humidity. Your driver is working by just allowing `CHIP_ID == 0x58`, humidity is outputed to 0%.

It could be great to support this sensor. I can make the modifications and test on the BMP280, but we need to choose how to support it:
 - just allowing 0x58
 - add a mode for only temperature and pressure
 - managing the 2 chips, and BMP can only di temperature and pressure, when BME can do temerature and pressure, or temperature, pressure and humidity.
 - something else.

What do you think?

### PR DESCRIPTION
**Pull request by TeXitoi**
Fix #1

### CODE REVIEW

**Review by sbruton — CHANGES_REQUESTED** [review]
awesome to hear that it works with the BMP280 just by changing the chip ID verification. Would you mind adding a hint about this to the documentation / README.md as well before I commit?

**Comment by TeXitoi** [comment]
Sure! Done! Just ask if you want something more!

**Comment by sbruton** [comment]
Awesome, thanks for the PR and for getting this working!

**Review by sbruton — APPROVED** [review]

**Comment by sbruton** [comment]
going to publish an updated crate shortly with your changes, let me know if you'd like to be added to the authors list @TeXitoi

**Comment by TeXitoi** [comment]
I don't care for the author list. Thanks for merging and publishing.

**Comment by TeXitoi** [comment]
@sbruton can you publish it as 0.1.1?

**Comment by sbruton** [comment]
done

**Comment by TeXitoi** [comment]
Thanks.

**Pull request merged**
